version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./upload:/app/upload
    env_file:
      - .env
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data: 